/* eslint-disable */
// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

declare global {
    interface Window {
        __TAURI_INVOKE__<T>(cmd: string, args?: Record<string, unknown>): Promise<T>;
    }
}

// Function avoids 'window not defined' in SSR
const invoke = () => window.__TAURI_INVOKE__;

/**
 * 获取所有种子。
 */
export function dbGetAllSeeds() {
    return invoke()<Seed[]>("db_get_all_seeds")
}

/**
 * 获取项。
 */
export function dbGetItems(filters: ItemFilters) {
    return invoke()<ItemResult>("db_get_items", { filters })
}

/**
 * 获取设置。
 */
export function dbGetSetting(key: string) {
    return invoke()<string>("db_get_setting", { key })
}

/**
 * 获取未读数量。
 */
export function dbGetUnreadCount(seedId: string | null) {
    return invoke()<number>("db_get_unread_count", { seedId })
}

/**
 * 插入种子。
 */
export function dbInsertSeed(name: string, url: string) {
    return invoke()<boolean>("db_insert_seed", { name,url })
}

/**
 * 将项标记为已读或未读。
 */
export function dbMarkItemRead(itemId: string, unread: boolean) {
    return invoke()<boolean>("db_mark_item_read", { itemId,unread })
}

/**
 * 修改设置。
 */
export function dbSetSetting(key: string, value: string) {
    return invoke()<boolean>("db_set_setting", { key,value })
}

/**
 * 种子项
 */
export type SeedItem = { id: string; seed_id: string; seed_name: string; title: string; author: string; desc: string | null; link: string; pub_date: string; unread: boolean }
export type ItemResult = { items: SeedItem[]; next_cursor: string | null }
/**
 * 种子
 */
export type Seed = { id: string; name: string; url: string; favicon: string | null; interval: number; last_fetched_at: string; last_fetch_ok: boolean }
export type ItemFilters = { seed_id: string | null; cursor: string | null; limit: string | null }
